# Understanding Data Types in Python

Effective data-driven science and computation requires understanding how data is stored and manipulated. This section outlines and contrasts how arrays of data are handled in the Python language itself, and how NumPy improves on this. Understanding this difference is fundamental to understanding much of the material throughout the rest of the course.

Python is simple to use. While a statically-typed language like C or Java requires each variable to be explicitly declared, a dynamically-typed language like Python skips this specification.

In C, the data types of each variable are explicitly declared, while in Python the types are dynamically inferred.
This means, for example, that we can assign any kind of data to any variable:

In [1]:
x = 4
x = "four"

This sort of flexibility is one piece that makes Python and other dynamically-typed languages convenient and easy to use. 

## 1.1. Data Types

We have several data types in python:
* None
* Numeric (int, float, complex, bool)
* List
* Tuple
* Set 
* String
* Range
* Dictionary (Map)

In [2]:
# NoneType
a = None
type(a)

NoneType

In [3]:
# int
a = 1+1
print(a)
type(a)

2


int

In [4]:
# complex
c = 1.5 + 0.5j 
type(c)

complex

In [5]:
c.real

1.5

In [6]:
c.imag

0.5

In [7]:
# boolean
d = 2 > 3
print(d)
type(d)

False


bool

## Python Lists

Let's consider now what happens when we use a Python data structure that holds many Python objects. The standard mutable multi-element container in Python is the list. We can create a list of integers as follows:

In [8]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
type(L[0])

int

Or, similarly, a list of strings:

In [10]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [11]:
type(L2[0])

str

Because of Python's dynamic typing, we can even create heterogeneous lists:

In [12]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

## Python Dictionaries

In [13]:
keys = [1, 2, 3, 4, 5]
values = ['monday', 'tuesday', 'wendsday', 'friday']

dictionary = dict(zip(keys, values))
dictionary

{1: 'monday', 2: 'tuesday', 3: 'wendsday', 4: 'friday'}

In [14]:
dictionary.get(1)

'monday'

In [15]:
dictionary[1]

'monday'

## Fixed-Type Arrays in Python

In [16]:
import numpy as np

First, we can use np.array to create arrays from Python lists:

In [17]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

Unlike python lists, NumPy is constrained to arrays that all contain the same type. 

If we want to explicitly set the data type of the resulting array, we can use the dtype keyword:



In [18]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

### Creating Arrays from Scratch

Especially for larger arrays, it is more efficient to create arrays from scratch using routines built into NumPy. Here are several examples:

In [19]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [23]:
# Create an array filled with a linear sequence
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)

np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])